services:
  - type: web
    name: churn-prediction-ai
    env: python
    buildCommand: "pip install -r requirements.txt && python model_training.py"
    startCommand: "uvicorn app:app --host 0.0.0.0 --port 10000"
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
